### ISSUE TITLE
Create release tags for old versions of the code

### ISSUE THREAD

**Issue by ulf1** [AgnieszkaFalenska/IMSnPars#1]
You can create releases here:
https://github.com/AgnieszkaFalenska/IMSnPars/releases

I would propose

tag version: `v0.1.0-acl2019`
branch: `acl2019`

and

tag version: `v0.2.0-iwpt2020`
branch: `iwpt2020`

**Comment by ulf1** [comment]
@AgnieszkaFalenska This is "documentation" issue (see "labels")

**Comment by AgnieszkaFalenska** [comment]
Done
