### ISSUE TITLE
Date and name is missing in the LICENSE file

### ISSUE THREAD

**Issue by ulf1** [AgnieszkaFalenska/IMSnPars#2]
see https://github.com/AgnieszkaFalenska/IMSnPars/blob/2ea7c8c9f6a29acc4b93d4ae7a642c21aa724955/LICENSE#L189

@AgnieszkaFalenska This is an issue with "invalid" label

**Comment by AgnieszkaFalenska** [comment]
I fixed it, thanks for pointing it out.
